# Generated by Django 5.0.1 on 2026-01-25 19:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyses", "0002_add_partner_information"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Eindeutiger Einladungscode",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_admin_code",
                    models.BooleanField(
                        default=False,
                        help_text="Von Admin für Marketing-Kampagnen erstellt",
                    ),
                ),
                (
                    "sent_to_emails",
                    models.TextField(
                        blank=True,
                        help_text="Komma-separierte Liste der Email-Adressen",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=10,
                        help_text="Maximale Anzahl der Verwendungen",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "credits_per_referral",
                    models.IntegerField(
                        default=3,
                        help_text="Credits für jeden erfolgreichen Referral",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional: Ablaufdatum", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User der den Code erstellt hat (null bei Admin-Codes)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_referral_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("signup_bonus", "Signup Bonus"),
                            ("referral_reward", "Referral Reward"),
                        ],
                        default="referral_reward",
                        max_length=20,
                    ),
                ),
                (
                    "credits_earned",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "earned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User der Credits erhalten hat (Referrer)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="referrals.referralcode",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User der den Code verwendet hat (neuer User)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_referral_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("link", "Link kopiert"),
                            ("other", "Sonstiges"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        default="score_card",
                        help_text="Type des Shares (score_card, badge, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Welche Analyse wurde geteilt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_events",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "share_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(fields=["code"], name="referral_co_code_0cdd0e_idx"),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(
                fields=["created_by"], name="referral_co_created_8da41e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(
                fields=["is_active"], name="referral_co_is_acti_365b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["earned_by"], name="referral_re_earned__737f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["used_by"], name="referral_re_used_by_03328a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["created_at"], name="referral_re_created_13a28d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(fields=["user"], name="share_event_user_id_51381a_idx"),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(
                fields=["platform"], name="share_event_platfor_a2852a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(
                fields=["created_at"], name="share_event_created_bbe3e1_idx"
            ),
        ),
    ]
