# Generated by Django 5.0.1 on 2026-01-25 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique question identifier (snake_case)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRUST", "Trust"),
                            ("BEHAVIOR", "Behavior"),
                            ("VALUES", "Values"),
                            ("DYNAMICS", "Dynamics"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "default_weight",
                    models.IntegerField(
                        default=3,
                        help_text="Default importance weight (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text_de", models.TextField(help_text="German question text")),
                ("text_en", models.TextField(help_text="English question text")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["key"], name="questions_key_38dc13_idx"),
                    models.Index(
                        fields=["category"], name="questions_categor_3ee678_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="questions_is_acti_ba6b3c_idx"
                    ),
                ],
            },
        ),
    ]
