# Generated by Django 5.0.1 on 2026-01-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_weightresponse"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="weightresponse",
            new_name="weight_resp_user_id_797d66_idx",
            old_name="weight_resp_user_id_cd5e8f_idx",
        ),
    ]
