# Generated by Django 5.0.1 on 2026-01-26 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0003_rename_weight_resp_user_id_cd5e8f_idx_weight_resp_user_id_797d66_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="default_weight",
        ),
        migrations.AddField(
            model_name="question",
            name="calculated_weight",
            field=models.FloatField(
                default=3.0,
                help_text="Calculated global weight from Z-Score standardization (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="weightresponse",
            name="importance",
            field=models.IntegerField(
                help_text="User's importance rating (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
