# Generated by Django 5.0.1 on 2026-01-25 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics Measurement ID (z.B. G-XXXXXXXXXX oder UA-XXXXXXXXX-X)",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(G|UA)-[A-Z0-9-]+$",
                                "Ungültiges GA-Format (z.B. G-XXXXXXXXXX oder UA-XXXXXXXXX-X)",
                            )
                        ],
                    ),
                ),
                (
                    "ga_enabled",
                    models.BooleanField(
                        default=False, help_text="Google Analytics aktivieren"
                    ),
                ),
                (
                    "hotjar_id",
                    models.CharField(
                        blank=True,
                        help_text="Hotjar Site ID (nur Zahlen)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Hotjar ID muss numerisch sein"
                            )
                        ],
                    ),
                ),
                (
                    "hotjar_enabled",
                    models.BooleanField(
                        default=False, help_text="Hotjar Tracking aktivieren"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Settings",
                "verbose_name_plural": "Analytics Settings",
                "db_table": "analytics_settings",
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("new_signups", models.IntegerField(default=0)),
                ("dau", models.IntegerField(default=0, help_text="Daily Active Users")),
                (
                    "mau",
                    models.IntegerField(
                        default=0, help_text="Monthly Active Users (rolling 30 days)"
                    ),
                ),
                (
                    "signup_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% der Besucher die sich registrieren",
                        max_digits=5,
                    ),
                ),
                ("total_analyses_created", models.IntegerField(default=0)),
                (
                    "avg_analyses_per_user",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_session_duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Durchschnittliche Session-Dauer in Sekunden",
                    ),
                ),
                (
                    "retention_day1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% der User die nach 1 Tag wiederkommen",
                        max_digits=5,
                    ),
                ),
                (
                    "retention_day7",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% der User die nach 7 Tagen wiederkommen",
                        max_digits=5,
                    ),
                ),
                (
                    "retention_day30",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% der User die nach 30 Tagen wiederkommen",
                        max_digits=5,
                    ),
                ),
                ("new_premium_users", models.IntegerField(default=0)),
                ("total_premium_users", models.IntegerField(default=0)),
                (
                    "free_to_premium_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% der Free User die Premium werden",
                        max_digits=5,
                    ),
                ),
                (
                    "revenue_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "arpu",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average Revenue Per User",
                        max_digits=10,
                    ),
                ),
                ("referral_codes_used", models.IntegerField(default=0)),
                (
                    "referral_conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="daily_metri_date_c5278a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("pages_visited", models.IntegerField(default=0)),
                ("analyses_created", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="user_sessio_user_id_eb91b5_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="user_sessio_session_e62ba3_idx"
                    ),
                ],
            },
        ),
    ]
