# Generated by Django 5.0.1 on 2026-01-25 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("article", "Artikel"),
                            ("video", "Videos"),
                            ("podcast", "Podcasts"),
                            ("case_study", "Case Studies"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="📝", help_text="Emoji Icon", max_length=50
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "db_table": "blog_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        default="landing_page",
                        help_text="Wo hat sich der User angemeldet?",
                        max_length=50,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_subscribed", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "content_markdown",
                    models.TextField(help_text="Markdown-formatted content"),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True, help_text="Auto-generated HTML from Markdown"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Kurze Zusammenfassung (max 300 Zeichen)",
                        max_length=300,
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(blank=True, help_text="URL zum Featured Image"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="YouTube/Vimeo URL (für Video-Posts)"
                    ),
                ),
                (
                    "podcast_url",
                    models.URLField(blank=True, help_text="Podcast Episode URL"),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Angezeigter Author-Name (falls abweichend)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("published", "Veröffentlicht")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO Title (max 60 Zeichen)",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO Description (max 160 Zeichen)",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Komma-separierte Keywords",
                        max_length=255,
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="blog.blogpost"
                    ),
                ),
            ],
            options={
                "db_table": "blog_tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="blog_posts_slug_b4ca25_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="blog_posts_status_d9ff7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "status"], name="blog_posts_categor_d81915_idx"
            ),
        ),
    ]
