# Generated by Django 5.0.1 on 2026-01-25 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_unlocked",
                    models.BooleanField(
                        default=False, help_text="Whether analysis is unlocked (paid)"
                    ),
                ),
                (
                    "responses",
                    models.JSONField(help_text="Question responses as JSON array"),
                ),
                (
                    "snapshot_weights",
                    models.JSONField(
                        help_text="Snapshot of weights used at analysis time"
                    ),
                ),
                (
                    "score_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total weighted score (0-10)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRUST", "Trust"),
                            ("BEHAVIOR", "Behavior"),
                            ("VALUES", "Values"),
                            ("DYNAMICS", "Dynamics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_scores",
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "category_scores",
            },
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analyses_user_id_0211ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["is_unlocked"], name="analyses_is_unlo_19ba22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryscore",
            index=models.Index(
                fields=["analysis", "category"], name="category_sc_analysi_e657a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryscore",
            unique_together={("analysis", "category")},
        ),
    ]
