# Generated by Django 5.0.1 on 2026-01-25 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0002_add_partner_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="partner_country",
            field=models.CharField(
                blank=True,
                help_text="Herkunftsland der Partnerin (optional)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="partner_age",
            field=models.IntegerField(
                blank=True,
                help_text="Alter der Partnerin (optional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="partner_name",
            field=models.CharField(
                blank=True,
                help_text="Name der analysierten Partnerin (optional)",
                max_length=100,
                null=True,
            ),
        ),
    ]
