# Generated by Django 5.0.1 on 2026-01-28 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0004_remove_snapshot_weights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="score_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total weighted score (0-5)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="categoryscore",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
