# Generated by Django 5.0.1 on 2026-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0005_alter_analysis_score_total_alter_categoryscore_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("partner_name", models.CharField(blank=True, max_length=100)),
                ("analysis_data", models.JSONField(help_text="Gespeicherte Antworten")),
                ("score_total", models.FloatField(blank=True, null=True)),
                ("converted_to_user", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("landing", "Landing Page"),
                            ("social", "Social Media"),
                            ("blog", "Blog"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "anonymous_analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"],
                        name="anonymous_a_email_df2efe_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="anonymous_a_session_f81281_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="anonymous_a_expires_61bf76_idx"
                    ),
                ],
            },
        ),
    ]
