# Generated by Django 5.0.1 on 2026-01-28 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyses", "0005_alter_analysis_score_total_alter_categoryscore_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("share_url", models.URLField(blank=True)),
                (
                    "share_image",
                    models.ImageField(blank=True, null=True, upload_to="shares/"),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("clicks_count", models.IntegerField(default=0)),
                ("conversions_count", models.IntegerField(default=0)),
                (
                    "shared_platform",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                            ("telegram", "Telegram"),
                            ("link", "Direct Link"),
                            ("other", "Other"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shared_analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="shared_anal_user_id_0f6007_idx",
                    ),
                    models.Index(
                        fields=["-views_count"], name="shared_anal_views_c_d53169_idx"
                    ),
                ],
            },
        ),
    ]
