# Generated by Django 5.0.1 on 2026-01-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="creditpurchase",
            new_name="credit_purc_user_id_288fbe_idx",
            old_name="credit_purc_user_id_a3b2c4_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_user_id_8725c3_idx",
            old_name="subscripti_user_id_d8e6a7_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_is_acti_238e40_idx",
            old_name="subscripti_is_acti_f9c4b2_idx",
        ),
    ]
