# Generated by Django 5.0.1 on 2026-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_extend_user_profile_and_ban_system"),
        ("accounts", "0002_userprofile_extended_registration"),
    ]

    operations = []
