# Generated by Django 5.0.1 on 2026-01-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_20260125_1857"),
        ("accounts", "0003_userbadge"),
    ]

    operations = []
