# Generated by Django 5.0.1 on 2026-01-25 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_0003_merge_20260125_1857_0003_userbadge"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userbadge",
            new_name="user_badges_user_id_b71e1f_idx",
            old_name="user_badges_user_id_a8c0a3_idx",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 1, 25, 19, 12, 7, 68245, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
