# Generated by Django 5.0.1 on 2026-01-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_user_badges_user_id_a8c0a3_idx_user_badges_user_id_b71e1f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google Suche"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("facebook", "Facebook"),
                    ("twitter_x", "Twitter/X"),
                    ("youtube", "YouTube"),
                    ("reddit", "Reddit"),
                    ("friend", "Freund/Bekannter"),
                    ("podcast", "Podcast"),
                    ("blog", "Blog/Artikel"),
                    ("advertisement", "Online-Werbung"),
                    ("app_store", "App Store"),
                    ("influencer", "Influencer-Empfehlung"),
                    ("news", "Nachrichten/Presse"),
                    ("other", "Sonstiges"),
                ],
                help_text="Wie hast du von uns erfahren?",
                max_length=20,
                null=True,
            ),
        ),
    ]
