# Generated by Django 5.0.1 on 2026-01-28 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_referral_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credits",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="points",
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily Tip"),
                            ("friend_activity", "Friend Activity"),
                            ("re_engagement", "Re-Engagement"),
                            ("streak_reminder", "Streak Reminder"),
                            ("credit_reminder", "Credit Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_notifications",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-sent_at"],
                        name="email_notif_user_id_c68f14_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-sent_at"],
                        name="email_notif_notific_3143ef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, help_text="Current weekly streak"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, help_text="All-time longest streak"),
                ),
                (
                    "last_active",
                    models.DateField(
                        blank=True, help_text="Last activity date", null=True
                    ),
                ),
                (
                    "streak_frozen",
                    models.BooleanField(
                        default=False, help_text="Streak freeze active?"
                    ),
                ),
                ("freeze_used_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_streaks",
                "indexes": [
                    models.Index(
                        fields=["user", "-current_streak"],
                        name="user_streak_user_id_2389b2_idx",
                    )
                ],
            },
        ),
    ]
