# Generated by Django 5.0.1 on 2026-01-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feedback",
            new_name="feedbacks_user_id_e7f492_idx",
            old_name="feedbacks_user_id_7b9c8a_idx",
        ),
        migrations.RenameIndex(
            model_name="feedback",
            new_name="feedbacks_status_65e9c3_idx",
            old_name="feedbacks_status_6a3d4f_idx",
        ),
    ]
